### ISSUE TITLE
Longitudinal analysis for samples with more than 2 timepoints?

### ISSUE THREAD

**Issue by carmennns2** [aplantin/pldist#1]
Hi, 

Is it possible to use pldist for samples with more than 2 timepoints? So far, only "exactly 2 unique time points" are allowed. 

Thanks!
Carmen

**Comment by aplantin** [comment]
Hi Carmen,

Yes, it's possible: use the paired=FALSE argument in each function to use
the longitudinal (rather than paired) transformations. Take a look at the
vignette and examples for more details -- you can run
vignette("introduction", package="pldist") after installing and loading the
package to bring the vignette up in the RStudio viewer pane. Let me know if
you have other questions after looking through the longitudinal examples in
the vignette.

Best,
Anna
